create table techused (
    id int not null auto_increment primary key,
    date      DATE,
    chrome    int,
    safari    int,
    firefox   int,
    tor       int,
    opera     int,
    ie        int,
    mac       int,
    linux     int,
    windows   int,
    vi        int,
    eclipse   int,
    netbeans  int,
    anaconda  int,
    sublime   int,
    php       int,
    perl      int,
    java      int,
    python    int,
    c         int,
    awk       int,
    latex     int,
    word      int,
    oo        int,
    excel     int,
    wordpress int,
    htmlcss   int
);
